//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.WebUI
{


    public partial class ContentPage
    {

        /// <summary>
        /// ltrHead control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrHead;

        /// <summary>
        /// ctrlSlideTop control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.WebUI.Controls.SlideTop ctrlSlideTop;

        /// <summary>
        /// ctrlBaiVietPublish control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.WebUI.Controls.ControlContentPage.BaiVietPublish ctrlBaiVietPublish;

        /// <summary>
        /// ctrlCategory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.WebUI.Controls.ControlContentPage.Category ctrlCategory;

        /// <summary>
        /// ctrlBaiVietGioiThieu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.WebUI.Controls.ControlContentPage.BaiVietGioiThieu ctrlBaiVietGioiThieu;

        /// <summary>
        /// ctrlDuAnTieuBieu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.WebUI.Controls.ControlContentPage.DuAnTieuBieu ctrlDuAnTieuBieu;

        /// <summary>
        /// ctrlFileDinhKemControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.WebUI.Controls.ControlContentPage.FileDinhKemControl ctrlFileDinhKemControl;

        /// <summary>
        /// ctrlDanhSachThanhVien control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.WebUI.Controls.DanhSachThanhVien ctrlDanhSachThanhVien;

        /// <summary>
        /// ltrBelow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrBelow;
    }
}
