using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetCMS.DataAccess
{
    /// <summary>
    /// Controller class for FriendlyUrl
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class FriendlyUrlController
    {
        // Preload our schema..
        FriendlyUrl thisSchemaLoad = new FriendlyUrl();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public FriendlyUrlCollection FetchAll()
        {
            FriendlyUrlCollection coll = new FriendlyUrlCollection();
            Query qry = new Query(FriendlyUrl.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public FriendlyUrlCollection FetchByID(object Id)
        {
            FriendlyUrlCollection coll = new FriendlyUrlCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public FriendlyUrlCollection FetchByQuery(Query qry)
        {
            FriendlyUrlCollection coll = new FriendlyUrlCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (FriendlyUrl.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (FriendlyUrl.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string SlugUrl,int PostId,int PostType,string Status)
	    {
		    FriendlyUrl item = new FriendlyUrl();
		    
            item.SlugUrl = SlugUrl;
            
            item.PostId = PostId;
            
            item.PostType = PostType;
            
            item.Status = Status;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string SlugUrl,int PostId,int PostType,string Status)
	    {
		    FriendlyUrl item = new FriendlyUrl();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.SlugUrl = SlugUrl;
				
			item.PostId = PostId;
				
			item.PostType = PostType;
				
			item.Status = Status;
				
	        item.Save(UserName);
	    }
    }
}
