using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetCMS.DataAccess
{
    /// <summary>
    /// Controller class for LoaiQuyen
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class LoaiQuyenController
    {
        // Preload our schema..
        LoaiQuyen thisSchemaLoad = new LoaiQuyen();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public LoaiQuyenCollection FetchAll()
        {
            LoaiQuyenCollection coll = new LoaiQuyenCollection();
            Query qry = new Query(LoaiQuyen.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public LoaiQuyenCollection FetchByID(object Id)
        {
            LoaiQuyenCollection coll = new LoaiQuyenCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public LoaiQuyenCollection FetchByQuery(Query qry)
        {
            LoaiQuyenCollection coll = new LoaiQuyenCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (LoaiQuyen.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (LoaiQuyen.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Ten,string Ma)
	    {
		    LoaiQuyen item = new LoaiQuyen();
		    
            item.Ten = Ten;
            
            item.Ma = Ma;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string Ten,string Ma)
	    {
		    LoaiQuyen item = new LoaiQuyen();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Ten = Ten;
				
			item.Ma = Ma;
				
	        item.Save(UserName);
	    }
    }
}
