using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetCMS.DataAccess
{
    /// <summary>
    /// Controller class for MenuWeb
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class MenuWebController
    {
        // Preload our schema..
        MenuWeb thisSchemaLoad = new MenuWeb();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public MenuWebCollection FetchAll()
        {
            MenuWebCollection coll = new MenuWebCollection();
            Query qry = new Query(MenuWeb.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public MenuWebCollection FetchByID(object Id)
        {
            MenuWebCollection coll = new MenuWebCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public MenuWebCollection FetchByQuery(Query qry)
        {
            MenuWebCollection coll = new MenuWebCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (MenuWeb.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (MenuWeb.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Ten,int? MenuChaId,string Slug,string MoTa,bool? MenuTren,bool? MenuDuoi)
	    {
		    MenuWeb item = new MenuWeb();
		    
            item.Ten = Ten;
            
            item.MenuChaId = MenuChaId;
            
            item.Slug = Slug;
            
            item.MoTa = MoTa;
            
            item.MenuTren = MenuTren;
            
            item.MenuDuoi = MenuDuoi;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string Ten,int? MenuChaId,string Slug,string MoTa,bool? MenuTren,bool? MenuDuoi)
	    {
		    MenuWeb item = new MenuWeb();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Ten = Ten;
				
			item.MenuChaId = MenuChaId;
				
			item.Slug = Slug;
				
			item.MoTa = MoTa;
				
			item.MenuTren = MenuTren;
				
			item.MenuDuoi = MenuDuoi;
				
	        item.Save(UserName);
	    }
    }
}
