using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetCMS.DataAccess
{
    /// <summary>
    /// Controller class for NganhDaoTao
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class NganhDaoTaoController
    {
        // Preload our schema..
        NganhDaoTao thisSchemaLoad = new NganhDaoTao();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public NganhDaoTaoCollection FetchAll()
        {
            NganhDaoTaoCollection coll = new NganhDaoTaoCollection();
            Query qry = new Query(NganhDaoTao.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public NganhDaoTaoCollection FetchByID(object Id)
        {
            NganhDaoTaoCollection coll = new NganhDaoTaoCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public NganhDaoTaoCollection FetchByQuery(Query qry)
        {
            NganhDaoTaoCollection coll = new NganhDaoTaoCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (NganhDaoTao.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (NganhDaoTao.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string MaNganh,string TenNganh,string SoNamDaoTao,string MoTaNgan,string NoiDung,int SoTinChi,string CreateBy,string UpdateBy,DateTime CreateDate,DateTime UpdateDate,string Status,int NhomNganh,string DieuKienNhapHoc,string HocPhi,string ThumbnailUrl,string Slug,int DisplayOrder,int ViewCount)
	    {
		    NganhDaoTao item = new NganhDaoTao();
		    
            item.MaNganh = MaNganh;
            
            item.TenNganh = TenNganh;
            
            item.SoNamDaoTao = SoNamDaoTao;
            
            item.MoTaNgan = MoTaNgan;
            
            item.NoiDung = NoiDung;
            
            item.SoTinChi = SoTinChi;
            
            item.CreateBy = CreateBy;
            
            item.UpdateBy = UpdateBy;
            
            item.CreateDate = CreateDate;
            
            item.UpdateDate = UpdateDate;
            
            item.Status = Status;
            
            item.NhomNganh = NhomNganh;
            
            item.DieuKienNhapHoc = DieuKienNhapHoc;
            
            item.HocPhi = HocPhi;
            
            item.ThumbnailUrl = ThumbnailUrl;
            
            item.Slug = Slug;
            
            item.DisplayOrder = DisplayOrder;
            
            item.ViewCount = ViewCount;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string MaNganh,string TenNganh,string SoNamDaoTao,string MoTaNgan,string NoiDung,int SoTinChi,string CreateBy,string UpdateBy,DateTime CreateDate,DateTime UpdateDate,string Status,int NhomNganh,string DieuKienNhapHoc,string HocPhi,string ThumbnailUrl,string Slug,int DisplayOrder,int ViewCount)
	    {
		    NganhDaoTao item = new NganhDaoTao();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.MaNganh = MaNganh;
				
			item.TenNganh = TenNganh;
				
			item.SoNamDaoTao = SoNamDaoTao;
				
			item.MoTaNgan = MoTaNgan;
				
			item.NoiDung = NoiDung;
				
			item.SoTinChi = SoTinChi;
				
			item.CreateBy = CreateBy;
				
			item.UpdateBy = UpdateBy;
				
			item.CreateDate = CreateDate;
				
			item.UpdateDate = UpdateDate;
				
			item.Status = Status;
				
			item.NhomNganh = NhomNganh;
				
			item.DieuKienNhapHoc = DieuKienNhapHoc;
				
			item.HocPhi = HocPhi;
				
			item.ThumbnailUrl = ThumbnailUrl;
				
			item.Slug = Slug;
				
			item.DisplayOrder = DisplayOrder;
				
			item.ViewCount = ViewCount;
				
	        item.Save(UserName);
	    }
    }
}
