using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetCMS.DataAccess
{
    /// <summary>
    /// Controller class for NguoiDung
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class NguoiDungController
    {
        // Preload our schema..
        NguoiDung thisSchemaLoad = new NguoiDung();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public NguoiDungCollection FetchAll()
        {
            NguoiDungCollection coll = new NguoiDungCollection();
            Query qry = new Query(NguoiDung.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public NguoiDungCollection FetchByID(object Id)
        {
            NguoiDungCollection coll = new NguoiDungCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public NguoiDungCollection FetchByQuery(Query qry)
        {
            NguoiDungCollection coll = new NguoiDungCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (NguoiDung.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (NguoiDung.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string HoVaTen,string Email,string SoDienThoai,DateTime? NgaySinh,string TenTruyCap,string MatKhau,string DiaChi,string AvataUrl,bool? TrangThai,DateTime? NgayTao,DateTime? ChinhSuaGanNhat)
	    {
		    NguoiDung item = new NguoiDung();
		    
            item.HoVaTen = HoVaTen;
            
            item.Email = Email;
            
            item.SoDienThoai = SoDienThoai;
            
            item.NgaySinh = NgaySinh;
            
            item.TenTruyCap = TenTruyCap;
            
            item.MatKhau = MatKhau;
            
            item.DiaChi = DiaChi;
            
            item.AvataUrl = AvataUrl;
            
            item.TrangThai = TrangThai;
            
            item.NgayTao = NgayTao;
            
            item.ChinhSuaGanNhat = ChinhSuaGanNhat;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string HoVaTen,string Email,string SoDienThoai,DateTime? NgaySinh,string TenTruyCap,string MatKhau,string DiaChi,string AvataUrl,bool? TrangThai,DateTime? NgayTao,DateTime? ChinhSuaGanNhat)
	    {
		    NguoiDung item = new NguoiDung();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.HoVaTen = HoVaTen;
				
			item.Email = Email;
				
			item.SoDienThoai = SoDienThoai;
				
			item.NgaySinh = NgaySinh;
				
			item.TenTruyCap = TenTruyCap;
				
			item.MatKhau = MatKhau;
				
			item.DiaChi = DiaChi;
				
			item.AvataUrl = AvataUrl;
				
			item.TrangThai = TrangThai;
				
			item.NgayTao = NgayTao;
				
			item.ChinhSuaGanNhat = ChinhSuaGanNhat;
				
	        item.Save(UserName);
	    }
    }
}
