using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace TBDCMS.DataAccess
{
    /// <summary>
    /// Controller class for DefaultSetting
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class DefaultSettingController
    {
        // Preload our schema..
        DefaultSetting thisSchemaLoad = new DefaultSetting();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public DefaultSettingCollection FetchAll()
        {
            DefaultSettingCollection coll = new DefaultSettingCollection();
            Query qry = new Query(DefaultSetting.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public DefaultSettingCollection FetchByID(object Id)
        {
            DefaultSettingCollection coll = new DefaultSettingCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public DefaultSettingCollection FetchByQuery(Query qry)
        {
            DefaultSettingCollection coll = new DefaultSettingCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (DefaultSetting.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (DefaultSetting.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public DefaultSetting Insert(DefaultSetting item)
	    {
		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
        public DefaultSetting Update(int Id, string KeyString, string ValueX)
        {
            DefaultSetting item = new DefaultSetting();
            item.MarkOld();
            item.IsLoaded = true;

            item.Id = Id;

            item.KeyString = KeyString;

            item.Value = ValueX;

            item.Save(UserName);
            return item;
        }
    }
}
