using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace TBDCMS.DataAccess
{
	/// <summary>
	/// Strongly-typed collection for the FriendlyUrl class.
	/// </summary>
    [Serializable]
	public partial class FriendlyUrlCollection : ActiveList<FriendlyUrl, FriendlyUrlCollection>
	{	   
		public FriendlyUrlCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>FriendlyUrlCollection</returns>
		public FriendlyUrlCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                FriendlyUrl o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the FriendlyUrl table.
	/// </summary>
	[Serializable]
	public partial class FriendlyUrl : ActiveRecord<FriendlyUrl>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public FriendlyUrl()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public FriendlyUrl(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public FriendlyUrl(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public FriendlyUrl(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("FriendlyUrl", TableType.Table, DataService.GetInstance("DataAcessProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "Id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarSlugUrl = new TableSchema.TableColumn(schema);
				colvarSlugUrl.ColumnName = "SlugUrl";
				colvarSlugUrl.DataType = DbType.AnsiString;
				colvarSlugUrl.MaxLength = 200;
				colvarSlugUrl.AutoIncrement = false;
				colvarSlugUrl.IsNullable = true;
				colvarSlugUrl.IsPrimaryKey = false;
				colvarSlugUrl.IsForeignKey = false;
				colvarSlugUrl.IsReadOnly = false;
				colvarSlugUrl.DefaultSetting = @"";
				colvarSlugUrl.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSlugUrl);
				
				TableSchema.TableColumn colvarPostId = new TableSchema.TableColumn(schema);
				colvarPostId.ColumnName = "PostId";
				colvarPostId.DataType = DbType.Int32;
				colvarPostId.MaxLength = 0;
				colvarPostId.AutoIncrement = false;
				colvarPostId.IsNullable = true;
				colvarPostId.IsPrimaryKey = false;
				colvarPostId.IsForeignKey = false;
				colvarPostId.IsReadOnly = false;
				colvarPostId.DefaultSetting = @"";
				colvarPostId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPostId);
				
				TableSchema.TableColumn colvarPostType = new TableSchema.TableColumn(schema);
				colvarPostType.ColumnName = "PostType";
				colvarPostType.DataType = DbType.Int32;
				colvarPostType.MaxLength = 0;
				colvarPostType.AutoIncrement = false;
				colvarPostType.IsNullable = true;
				colvarPostType.IsPrimaryKey = false;
				colvarPostType.IsForeignKey = false;
				colvarPostType.IsReadOnly = false;
				colvarPostType.DefaultSetting = @"";
				colvarPostType.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPostType);
				
				TableSchema.TableColumn colvarStatus = new TableSchema.TableColumn(schema);
				colvarStatus.ColumnName = "Status";
				colvarStatus.DataType = DbType.String;
				colvarStatus.MaxLength = 50;
				colvarStatus.AutoIncrement = false;
				colvarStatus.IsNullable = true;
				colvarStatus.IsPrimaryKey = false;
				colvarStatus.IsForeignKey = false;
				colvarStatus.IsReadOnly = false;
				
						colvarStatus.DefaultSetting = @"('Active')";
				colvarStatus.ForeignKeyTableName = "";
				schema.Columns.Add(colvarStatus);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DataAcessProvider"].AddSchema("FriendlyUrl",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("SlugUrl")]
		[Bindable(true)]
		public string SlugUrl 
		{
			get { return GetColumnValue<string>(Columns.SlugUrl); }
			set { SetColumnValue(Columns.SlugUrl, value); }
		}
		  
		[XmlAttribute("PostId")]
		[Bindable(true)]
		public int PostId 
		{
			get { return GetColumnValue<int>(Columns.PostId); }
			set { SetColumnValue(Columns.PostId, value); }
		}
		  
		[XmlAttribute("PostType")]
		[Bindable(true)]
		public int PostType 
		{
			get { return GetColumnValue<int>(Columns.PostType); }
			set { SetColumnValue(Columns.PostType, value); }
		}
		  
		[XmlAttribute("Status")]
		[Bindable(true)]
		public string Status 
		{
			get { return GetColumnValue<string>(Columns.Status); }
			set { SetColumnValue(Columns.Status, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varSlugUrl,int varPostId,int varPostType,string varStatus)
		{
			FriendlyUrl item = new FriendlyUrl();
			
			item.SlugUrl = varSlugUrl;
			
			item.PostId = varPostId;
			
			item.PostType = varPostType;
			
			item.Status = varStatus;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varSlugUrl,int varPostId,int varPostType,string varStatus)
		{
			FriendlyUrl item = new FriendlyUrl();
			
				item.Id = varId;
			
				item.SlugUrl = varSlugUrl;
			
				item.PostId = varPostId;
			
				item.PostType = varPostType;
			
				item.Status = varStatus;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn SlugUrlColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn PostIdColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn PostTypeColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn StatusColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"Id";
			 public static string SlugUrl = @"SlugUrl";
			 public static string PostId = @"PostId";
			 public static string PostType = @"PostType";
			 public static string Status = @"Status";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
