using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetCMS.DataAccess
{
    /// <summary>
    /// Controller class for LichSuHeThong
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class LichSuHeThongController
    {
        // Preload our schema..
        LichSuHeThong thisSchemaLoad = new LichSuHeThong();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public LichSuHeThongCollection FetchAll()
        {
            LichSuHeThongCollection coll = new LichSuHeThongCollection();
            Query qry = new Query(LichSuHeThong.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public LichSuHeThongCollection FetchByID(object Id)
        {
            LichSuHeThongCollection coll = new LichSuHeThongCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public LichSuHeThongCollection FetchByQuery(Query qry)
        {
            LichSuHeThongCollection coll = new LichSuHeThongCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (LichSuHeThong.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (LichSuHeThong.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public LichSuHeThong Insert(LichSuHeThong item)
        {
		    
		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string NguoiTao,string HanhDong,string TenNhom,string TenDoiTuong,DateTime CreateDate)
	    {
		    LichSuHeThong item = new LichSuHeThong();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.NguoiTao = NguoiTao;
				
			item.HanhDong = HanhDong;
				
			item.TenNhom = TenNhom;
				
			item.TenDoiTuong = TenDoiTuong;
				
			item.CreateDate = CreateDate;
				
	        item.Save(UserName);
	    }
    }
}
