using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetCMS.DataAccess
{
    /// <summary>
    /// Controller class for MenuWebTren
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class MenuWebTrenController
    {
        // Preload our schema..
        MenuWebTren thisSchemaLoad = new MenuWebTren();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public MenuWebTrenCollection FetchAll()
        {
            MenuWebTrenCollection coll = new MenuWebTrenCollection();
            Query qry = new Query(MenuWebTren.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public MenuWebTrenCollection FetchByID(object Id)
        {
            MenuWebTrenCollection coll = new MenuWebTrenCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public MenuWebTrenCollection FetchByQuery(Query qry)
        {
            MenuWebTrenCollection coll = new MenuWebTrenCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (MenuWebTren.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (MenuWebTren.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
        public MenuWebTren Insert(MenuWebTren menuWebTren)
        {
            MenuWebTren item = new MenuWebTren();
            menuWebTren.Save(UserName);
            return menuWebTren;
        }

        /// <summary>
        /// Updates a record, can be used with the Object Data Source
        /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public MenuWebTren Update(MenuWebTren menuWebTren)
	    {
		    MenuWebTren item = new MenuWebTren();
	        menuWebTren.Save(UserName);
            return menuWebTren;
	    }
    }
}
