using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace TBDCMS.DataAccess
{
    /// <summary>
    /// Controller class for NguoiDung
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class NguoiDungController
    {
        // Preload our schema..
        NguoiDung thisSchemaLoad = new NguoiDung();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public NguoiDungCollection FetchAll()
        {
            NguoiDungCollection coll = new NguoiDungCollection();
            Query qry = new Query(NguoiDung.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public NguoiDungCollection FetchByID(object Id)
        {
            NguoiDungCollection coll = new NguoiDungCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public NguoiDungCollection FetchByQuery(Query qry)
        {
            NguoiDungCollection coll = new NguoiDungCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (NguoiDung.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (NguoiDung.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public NguoiDung Insert(NguoiDung nguoiDung)
	    {
            nguoiDung.Save(UserName);
            return nguoiDung;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
        public NguoiDung Update(NguoiDung nguoiDung)
        {
            nguoiDung.Save(UserName);
            return nguoiDung;
        }
    }
}
