using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetCMS.DataAccess
{
    /// <summary>
    /// Controller class for NhomHinhAnh
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class NhomHinhAnhController
    {
        // Preload our schema..
        NhomHinhAnh thisSchemaLoad = new NhomHinhAnh();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public NhomHinhAnhCollection FetchAll()
        {
            NhomHinhAnhCollection coll = new NhomHinhAnhCollection();
            Query qry = new Query(NhomHinhAnh.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public NhomHinhAnhCollection FetchByID(object Id)
        {
            NhomHinhAnhCollection coll = new NhomHinhAnhCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public NhomHinhAnhCollection FetchByQuery(Query qry)
        {
            NhomHinhAnhCollection coll = new NhomHinhAnhCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (NhomHinhAnh.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (NhomHinhAnh.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public NhomHinhAnh Insert(string HinhAnhUrl,int BaiVietId)
	    {
		    NhomHinhAnh item = new NhomHinhAnh();
		    
            item.HinhAnhUrl = HinhAnhUrl;
            
            item.BaiVietId = BaiVietId;
            
	    
		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public NhomHinhAnh Update(int Id,string HinhAnhUrl,int BaiVietId)
	    {
		    NhomHinhAnh item = new NhomHinhAnh();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.HinhAnhUrl = HinhAnhUrl;
				
			item.BaiVietId = BaiVietId;
				
	        item.Save(UserName);
            return item;

        }
    }
}
