using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace TBDCMS.DataAccess
{
	/// <summary>
	/// Strongly-typed collection for the NhomHinhAnh class.
	/// </summary>
    [Serializable]
	public partial class NhomHinhAnhCollection : ActiveList<NhomHinhAnh, NhomHinhAnhCollection>
	{	   
		public NhomHinhAnhCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>NhomHinhAnhCollection</returns>
		public NhomHinhAnhCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                NhomHinhAnh o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the NhomHinhAnh table.
	/// </summary>
	[Serializable]
	public partial class NhomHinhAnh : ActiveRecord<NhomHinhAnh>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public NhomHinhAnh()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public NhomHinhAnh(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public NhomHinhAnh(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public NhomHinhAnh(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("NhomHinhAnh", TableType.Table, DataService.GetInstance("DataAcessProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "Id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarHinhAnhUrl = new TableSchema.TableColumn(schema);
				colvarHinhAnhUrl.ColumnName = "HinhAnhUrl";
				colvarHinhAnhUrl.DataType = DbType.AnsiString;
				colvarHinhAnhUrl.MaxLength = 500;
				colvarHinhAnhUrl.AutoIncrement = false;
				colvarHinhAnhUrl.IsNullable = false;
				colvarHinhAnhUrl.IsPrimaryKey = false;
				colvarHinhAnhUrl.IsForeignKey = false;
				colvarHinhAnhUrl.IsReadOnly = false;
				colvarHinhAnhUrl.DefaultSetting = @"";
				colvarHinhAnhUrl.ForeignKeyTableName = "";
				schema.Columns.Add(colvarHinhAnhUrl);
				
				TableSchema.TableColumn colvarBaiVietId = new TableSchema.TableColumn(schema);
				colvarBaiVietId.ColumnName = "BaiVietId";
				colvarBaiVietId.DataType = DbType.Int32;
				colvarBaiVietId.MaxLength = 0;
				colvarBaiVietId.AutoIncrement = false;
				colvarBaiVietId.IsNullable = false;
				colvarBaiVietId.IsPrimaryKey = false;
				colvarBaiVietId.IsForeignKey = true;
				colvarBaiVietId.IsReadOnly = false;
				colvarBaiVietId.DefaultSetting = @"";
				
					colvarBaiVietId.ForeignKeyTableName = "BaiViet";
				schema.Columns.Add(colvarBaiVietId);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DataAcessProvider"].AddSchema("NhomHinhAnh",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("HinhAnhUrl")]
		[Bindable(true)]
		public string HinhAnhUrl 
		{
			get { return GetColumnValue<string>(Columns.HinhAnhUrl); }
			set { SetColumnValue(Columns.HinhAnhUrl, value); }
		}
		  
		[XmlAttribute("BaiVietId")]
		[Bindable(true)]
		public int BaiVietId 
		{
			get { return GetColumnValue<int>(Columns.BaiVietId); }
			set { SetColumnValue(Columns.BaiVietId, value); }
		}
		
		#endregion
		
		
			
		
		#region ForeignKey Properties
		
		/// <summary>
		/// Returns a BaiViet ActiveRecord object related to this NhomHinhAnh
		/// 
		/// </summary>
		public TBDCMS.DataAccess.BaiViet BaiViet
		{
			get { return TBDCMS.DataAccess.BaiViet.FetchByID(this.BaiVietId); }
			set { SetColumnValue("BaiVietId", value.Id); }
		}
		
		
		#endregion
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varHinhAnhUrl,int varBaiVietId)
		{
			NhomHinhAnh item = new NhomHinhAnh();
			
			item.HinhAnhUrl = varHinhAnhUrl;
			
			item.BaiVietId = varBaiVietId;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varHinhAnhUrl,int varBaiVietId)
		{
			NhomHinhAnh item = new NhomHinhAnh();
			
				item.Id = varId;
			
				item.HinhAnhUrl = varHinhAnhUrl;
			
				item.BaiVietId = varBaiVietId;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn HinhAnhUrlColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn BaiVietIdColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"Id";
			 public static string HinhAnhUrl = @"HinhAnhUrl";
			 public static string BaiVietId = @"BaiVietId";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
