using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace TBDCMS.DataAccess
{
    /// <summary>
    /// Controller class for VaiTro_DanhMuc_LoaiQuyen_ChiTiet
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class VaiTroDanhMucLoaiQuyenChiTietController
    {
        // Preload our schema..
        VaiTroDanhMucLoaiQuyenChiTiet thisSchemaLoad = new VaiTroDanhMucLoaiQuyenChiTiet();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public VaiTroDanhMucLoaiQuyenChiTietCollection FetchAll()
        {
            VaiTroDanhMucLoaiQuyenChiTietCollection coll = new VaiTroDanhMucLoaiQuyenChiTietCollection();
            Query qry = new Query(VaiTroDanhMucLoaiQuyenChiTiet.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public VaiTroDanhMucLoaiQuyenChiTietCollection FetchByID(object Id)
        {
            VaiTroDanhMucLoaiQuyenChiTietCollection coll = new VaiTroDanhMucLoaiQuyenChiTietCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public VaiTroDanhMucLoaiQuyenChiTietCollection FetchByQuery(Query qry)
        {
            VaiTroDanhMucLoaiQuyenChiTietCollection coll = new VaiTroDanhMucLoaiQuyenChiTietCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (VaiTroDanhMucLoaiQuyenChiTiet.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (VaiTroDanhMucLoaiQuyenChiTiet.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
        public VaiTroDanhMucLoaiQuyenChiTiet Insert(VaiTroDanhMucLoaiQuyenChiTiet vaiTroDanhMucLoaiQuyenChiTiet)
        {
            VaiTroDanhMucLoaiQuyenChiTiet item = new VaiTroDanhMucLoaiQuyenChiTiet();

            vaiTroDanhMucLoaiQuyenChiTiet.Save(UserName);
            return vaiTroDanhMucLoaiQuyenChiTiet;
        }

        /// <summary>
        /// Updates a record, can be used with the Object Data Source
        /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public VaiTroDanhMucLoaiQuyenChiTiet Update(VaiTroDanhMucLoaiQuyenChiTiet vaiTroDanhMucLoaiQuyenChiTiet)
	    {
		    VaiTroDanhMucLoaiQuyenChiTiet item = new VaiTroDanhMucLoaiQuyenChiTiet();
				
	        vaiTroDanhMucLoaiQuyenChiTiet.Save(UserName);
            return vaiTroDanhMucLoaiQuyenChiTiet;
	    }
    }
}
